services:
  backend:
    container_name: backend
    build:
      context: ./ts-backend
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - ./ts-backend:/app
      - /app/node_modules
    command: npm run dev
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        FRONTEND_PORT: 8001
    environment:
      FRONTEND_PORT: 8001
      BACKEND_PORT: 8000
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 8001:8001
    restart: on-failure
